### ISSUE TITLE
Great F-in plugin - I am also OCD :)

### ISSUE THREAD

**Issue by mikicherniak** [basiclines/figma-super-tidy#6]
Would it be possible to add some functionallity?
I would love to be able to reorder all the layers in a design to be sorted acording to their visual placement left-to-right, top-to-bottom..
(similar to what you have done here with the frames).
e.g:
Title
Subtitle
icon
breakline
how it works section (component)
 > how it works step 1
   > icon
   > text
 > how it works step 2
   > icon
   > text

So the layers correlate the visuo-logical order of the design :)

How I was clear enough.
Thanks anyway!
Michael.

**Comment by basiclines** [comment]
Highly related with #7 as both issues are about making the plugin work also with other node types apart from frames. Will look into it soon!

**Comment by basiclines** [comment]
As I've just commented on #7 I've tested the plugin with several node types and it works in all of them
