### ISSUE TITLE
Reorder does not work (inside frames)

### ISSUE THREAD

**Issue by leadelazer** [basiclines/figma-super-tidy#7]
It wokred fine when I first tried the plugin on launch day but now it throws some errors, at least with my installation (current desktop app for mac). I'll attach a log file from my console...

[www.figma.com-1566132155008.log](https://github.com/basiclines/figma-super-tidy/files/3513025/www.figma.com-1566132155008.log)

just tested ungrouping the items I wanted to reorder, that worked so I changed the title of the issue bc it only does not work if the items are inside a frame.

**Comment by basiclines** [comment]
Hi Lea, this is something I hadn't I mind as the plugin is mainly intended to be used to order Frames, but it think it is worthy to make it work also with other kind of nodes. Will keep the issue open until I make the fix!

**Comment by leadelazer** [comment]
Thank, that would be great!

**Comment by basiclines** [comment]
Just tested and it works perfectly with shapes and text layers also!

**Comment by basiclines** [comment]
Reopening as I misunderstood this issue!

**Comment by basiclines** [comment]
Now it is fixed for the next release!
